of: overwriter: Fix mixed declarations in patch_device_tree
Move the declarations of `op_input` and `final_len` to the beginning of
the `patch_device_tree` function in overwrite_config_loader.c to comply
with pre-C99 standards. This addresses the following compiler errors:

- drivers/of/overwriter/overwrite_config_loader.c:340:15: error: mixing
  declarations and code is incompatible with standards before C99
- drivers/of/overwriter/overwrite_config_loader.c:480:16: error: mixing
  declarations and code is incompatible with standards before C99

The change ensures variables are declared at the block start, maintaining
compatibility without altering functionality.

Signed-off-by: brokestar233 <3765589194@qq.com>